### PR TITLE
Setting up basic layout and login page

### PR DESCRIPTION
**Pull request by maplegilbs**
Apologies for not breaking this PR down into two separate ones, logically layout and login are different items.

In this PR
- created basic one column 3 row layout - header/content/footer
- implemented react-burger-menu to create slide-out sidebar menu
- brought in font-awesome package for icons
- created login page (and related components) utilizing firebase auth for login with email and password

A couple of notes:
- Please do not hold back on suggestions / criticisms etc.  Still quite new to this. The more feedback you provide the better the code in these PRs will (hopefully) become
- Currently using vanilla CSS for ease of quick setup (not familiar with tailwinds)
- Have not implemented any authentication / page protection beyond very basic login / logout
- Utilizing query strings to set the Toaster Notification currently
- Attempting to follow BEM naming convention for CSS (open to other approaches)

Thanks
-Scott

### CODE REVIEW

**Comment by NathanWEdwards** [comment]
[app/login/page.tsx:12](https://github.com/codeforbtv/baby-equipment-exchange/blob/initial-layout-and-login/src/app/login/page.tsx?plain=1#L12):
> Should we have a function exported from `api/firebase.ts`, or elsewhere, to manage calls to `initializeAuth()` and `getAuth()` from the `firebase/auth` modular API?
> https://firebase.google.com/docs/auth/web/password-auth
> https://firebase.google.com/docs/auth/web/custom-dependencies

**Comment by bryanparmelee** [comment]
@NathanWEdwards I think so. I usually export functions directly from the firebase config file that manage calls to the API to keep all the Firebase logic in one place. I think there was some miscommunication earlier and I didn't realize Scott was also working on Auth stuff. I should have time later this afternoon to refactor things a bit. Thanks for banging this out @maplegilbs!

**Comment by maplegilbs** [comment]
That would have been helpful to mention eh, seeing as how that is an ignored file.  Like Bryan I left that all in the firebase config file as well - just a simple 
```
// Initialize Firebase
const app = initializeApp(firebaseConfig);
export const auth = getAuth(app);
```
At the bottom

**Comment by bryanparmelee** [comment]
@maplegilbs yup, but it looks like Nathan has already the firebase app initialization happening in the api/firebase.ts file he created, so I think it makes the most sense to include all the auth stuff there as well. I can make that happen. 
No worries about the confusion, I'm still pretty new to coding with a team as well, ha.

**Comment by NathanWEdwards** [comment]
I'm storing the firebaseConfig object within firebase-config.js .. I didn't want to expose things like the API key, authentication domain, and storage bucket? Although security policies and Firebase rules govern the security of the application, not necessarily exposing an API key, I'm superstitious about providing any advantage toward denial-of-service and phishing practices. I always omit these kinds of things from public visibility.

**Comment by bryanparmelee** [comment]
Totally agree. I usually create environment variables for each of the config values, but gitignoring the config file and initializing the app elsewhere makes a lot of sense.

**Comment by NathanWEdwards** [comment]
I really like the Login page, thanks @maplegilbs.

[./src/components/ToasterNotification.tsx:4](https://github.com/codeforbtv/baby-equipment-exchange/blob/d1ad8dc4d3fc6d05512eedf2d0b3d657f05da49a/src/components/ToasterNotification.tsx#L4) has a typo.

[./src/components/ToasterNotification.tsx:22](https://github.com/codeforbtv/baby-equipment-exchange/blob/d1ad8dc4d3fc6d05512eedf2d0b3d657f05da49a/src/components/ToasterNotification.tsx#L22) 'status' props.status is possibly null. 'null' can't be provided as an index to statusLookup[]. A default value should be set for props.status or **NotificationProps.status should not ever be null**. .src/app/login/page.tsx performs a null-check on the input passed to the ToasterNotification component.

In my browser, the slider menu opens on the opposite side of the burger icon:
Baby_Equipment_Exchange_slider

When authentication fails, authentication failure details are present in the console.
Baby_Equipment_Exchange_console_errors_on_failed_login

**Comment by maplegilbs** [comment]
@NathanWEdwards - made the changes you noted and pushed a new commit specifically:
- moved the slide-out menu to the right
- removed the console.error from the login page outputing authentication failure details to the console
- fixed the type error in the ToaterNotification component

Note we will need to change the imports on the login page after Bryan's changes are merged to reflect the new location of the firebase auth

**Pull request merged**
